Qubit tracking
TartuQC/qccdSimulator pull request #2
Opened 2021-03-12 15:45 UTC by alejandrovgonzalez

2021-03-12 15:59 UTC, alejandrovgonzalez commented
TODO:
* Check coherence between topology components
* Create Watcher
* Consistent method names between commits
* Consistent and correct documentation

2021-03-18 17:45 UTC, Hopery requested changes
Some changes.

2021-03-18 17:45 UTC, Hopery commented on src/qccdParser.jl
> +function _createJunctions(shuttles::Array{ShuttleInfoJSON}, junctions::Array{JunctionInfoJSON})::Dict{Int64,Junction}
The lines are too big. I think it is better if we split them.

2021-03-18 17:45 UTC, Hopery commented on src/qccdParser.jl
> +        end
I think is more elegant something like:
```Julia
!haskey(res, j.id) || throw(ArgumentError("Repeated junction ID: " * j.id * " . Make sure the IDs are unique."))
```
Also, message errors must be consistent

2021-03-18 17:45 UTC, Hopery commented on src/qccdParser.jl
> +            end
Since it's a simple if-else, maybe it can be better to use a ternary.

2021-03-18 17:45 UTC, Hopery commented on src/types/device.jl
> +            " ends. It should have ", typesSizes[type], " ends.")))
I think is better to use ` * ` to concatenate strings. Also, maybe the lines are too long.

2021-03-18 17:50 UTC, alejandrovgonzalez commented on src/qccdParser.jl
> +        throw(err)
Catching the error and re-throwing it may not be necessary.

2021-03-18 17:50 UTC, alejandrovgonzalez commented on src/qccdParser.jl
> +    for trap in trapJSON.traps
\in

2021-03-19 15:34 UTC, Hopery approved these changes

2021-03-25 19:10 UTC, alejandrovgonzalez commented on src/qccdParser.jl
> +Creates a dictionary of qubits using a object TrapJSON.
dead code

2021-03-25 19:22 UTC, alejandrovgonzalez commented on src/qccdParser.jl
> +Throws error when:
Error descriptions are wrong, here and in called functions.

2021-03-25 19:31 UTC, merged